### ISSUE TITLE
Failing tests on local master

### ISSUE THREAD

**Issue by jarednielsen** [awslabs/sagemaker-debugger#12]
test_hook_all_zero.py is failing both tests on master when run locally.
![Screen Shot 2019-11-19 at 4 50 38 PM](https://user-images.githubusercontent.com/4564897/69199441-ce6c8700-0aec-11ea-92f4-6c6900a797f6.png)

test_uninint_sess_run is failing on master when run locally
![Screen Shot 2019-11-19 at 4 51 46 PM](https://user-images.githubusercontent.com/4564897/69199492-f360fa00-0aec-11ea-9221-e9634b2dd10d.png)
![Screen Shot 2019-11-19 at 4 51 56 PM](https://user-images.githubusercontent.com/4564897/69199498-f5c35400-0aec-11ea-91e4-398dd53904e0.png)

test_outdir_sagemaker is failing on master when run locally on Mac because no permission to write to the directory 'my'.

**Comment by jarednielsen** [comment]
Still occurring. `pytest -W=ignore tests/mxnet --skipslow` succeeds, but `pytest -W=ignore tests --skipslow` fails.

**Comment by leleamol** [comment]
The test_hook_all_zero.py is part of CI that runs for every PR>
I confirmed that it is passing in the CI.
