### ISSUE TITLE
Name clash when operator is called multiple times during forward pass

### ISSUE THREAD

**Issue by NRauschmayr** [awslabs/sagemaker-debugger#187]
When running debugger in Resnet model training,  debugger only stores one activation output tensor per basic block, while there should be 2. Here is a code snippet:

```
class BasicBlock(nn.Module):
    
    def __init__():
        super(BasicBlock, self).__init__()

        [...]

        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = norm_layer(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = norm_layer(planes)

    def forward(self, x):
        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        return out
```

`self.relu` is called twice but only last one will be stored by debugger. This happens because both tensors have the same name. I avoided this problem by customizing the hook and [keeping track of tensor names](https://github.com/NRauschmayr/amazon-sagemaker-examples/blob/update_iterative_model_pruning/sagemaker-debugger/pytorch_iterative_model_pruning/src/custom_hook.py#L20) during forward pass. While this works, it is not the nicest solution. Is there another workaround?

**Comment by NihalHarish** [comment]
A fix for this issue is currently WIP.
Progress can be viewed here:
https://github.com/awslabs/sagemaker-debugger/compare/master...pytorch-tensor-bug
