### ISSUE TITLE
Cannot install it via pip-tools

### ISSUE THREAD

**Issue by cosmincatalin** [awslabs/sagemaker-debugger#85]
Hi,

I'm trying to use pip-tools to install the package. the configuration I want is:

```
numpy==1.14.6
mxnet==1.4.1
boto3==1.10.32
stepfunctions==1.0.0.1
pur==5.2.2
sagemaker-experiments==0.1.2
smdebug==0.4.14
```

However I get thrown:

```
Finding the best candidates:
  found candidate aioboto3==6.4.1 (constraint was ==6.4.1)
Could not find a version that matches aiobotocore==0.11.0,~=0.10.2
Tried: 0.0.5, 0.0.6, 0.1.1, 0.2.0, 0.2.1, 0.2.1, 0.2.2, 0.2.2, 0.2.3, 0.2.3, 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.3.2, 0.3.2, 0.3.3, 0.3.3, 0.4.0, 0.4.0, 0.4.1, 0.4.1, 0.4.2, 0.4.2, 0.4.3, 0.4.3, 0.4.4, 0.4.4, 0.4.5, 0.4.5, 0.5.0, 0.5.0, 0.5.1, 0.5.1, 0.5.2, 0.5.2, 0.5.3, 0.5.3, 0.6.0, 0.6.0, 0.7.0, 0.7.0, 0.8.0, 0.8.0, 0.9.0, 0.9.1, 0.9.1, 0.9.2, 0.9.2, 0.9.3, 0.9.3, 0.9.4, 0.9.4, 0.10.0, 0.10.0, 0.10.1, 0.10.1, 0.10.2, 0.10.2, 0.10.3, 0.10.3, 0.10.4, 0.10.4, 0.11.0, 0.11.0
Skipped pre-versions: 0.6.1a0, 0.6.1a0
There are incompatible versions in the resolved dependencies.
```

I would think that my requirements file is fairly basic. Is this something you can help with?

**Comment by jarednielsen** [comment]
Hi Cosmin, thanks for letting us know! We've been able to recreate your issue, and we're working on a fix which will remove aioboto3 and fix the incompatible versions. It may be a few days until that's released. In the meantime, we recommend using `pip install smdebug` or `pip install -r requirements.txt` directly rather than pip-tools.

**Comment by rahul003** [comment]
Hi cosmincatalin@, we have merged a change to remove our dependency on aioboto3. We're working on making a new release with that change this week. Meanwhile you can install it by building a whl from the current source with `python setup.py bdist_wheel --universal`. 
I'll update this thread when we have a new release on pypi
