### ISSUE TITLE
Create and teardown S3 state, instead of relying on it being there

### ISSUE THREAD

**Issue by jarednielsen** [awslabs/sagemaker-debugger#93]
That way our test suite is standalone, without undocumented state.

```
s3://smdebug-testing/resources/event-files-missing
s3://smdebug-testing/resources/has_step_scenarios
s3://smdebug-testing/resources/one-index-files
s3://smdebug-testing/resources/dist-logs-10
```

**Comment by Vikas-kum** [comment]
I dont think we should teardown. Data shouldn't change helps me in trusting that there was no regression.

**Comment by jarednielsen** [comment]
Agreed that the data shouldn't change. The data should come from the test though, that's the point of a "unit" test.

**Comment by Vikas-kum** [comment]
> Agreed that the data shouldn't change. The data should come from the test though, that's the point of a "unit" test.

If you are creating and deleting data in s3, then there is chance that you would mess with the data. 
This is not unit test. If you want unit test, you should mock s3 client and not hit s3. 
Hope this makes it clear. Please create a new issue with where s3 access needs to be mocked and move the existing test to integration test. 
Accessing s3 data should be part of basic sanity testing which runs in CI and it is ok to have data there and there is some friction in changing data. If test breaks on existing data, then I want some eyes on it, rahther than making it easy to modify the data.
